exclude: 'docs|.git|.tox'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [ '--maxkb=1024' ]
      - id: trailing-whitespace
        exclude_types: [ svg ]
      - id: end-of-file-fixer
        exclude_types: [ svg ]
      - id: debug-statements

repos:
  - repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.0.2
    hooks:
      - id: packer_fmt
